Repository QualityCore/QualityCore-backend, pull requests merged in 2025-02, with the labels that each got.

#48 작업장정보등록 백엔드 수정및 컨피그 URL 수정
  src/main/java/com/org/qualitycore/config/CorsConfig.java
  src/main/java/com/org/qualitycore/masterdata/model/dto/WorkplaceScheduleDTO.java
  src/main/java/com/org/qualitycore/masterdata/model/entity/WorkplaceSchedule.java
  src/main/java/com/org/qualitycore/masterdata/model/repository/WorkplaceScheduleRepository.java
  src/main/java/com/org/qualitycore/standardinformation/controller/StandardInformationController.java
  src/main/java/com/org/qualitycore/standardinformation/model/dto/WorkplaceDTO.java
  src/main/java/com/org/qualitycore/standardinformation/model/entity/StandardInformationMessage.java
  src/main/java/com/org/qualitycore/standardinformation/model/entity/Workplace.java
  src/main/java/com/org/qualitycore/standardinformation/model/repository/WorkplaceRepository.java
  src/main/java/com/org/qualitycore/standardinformation/model/service/StandardInformationService.java
Labels: 도와주십쇼😢

#52 2/14 작업장정보 crud 데이터 변경으로 오류난 부분 수정완료
  .github/DISCUSSION_TEMPLATE/MEETING.yml
  .github/ISSUE_TEMPLATE/css-style.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-issue.md
  .github/ISSUE_TEMPLATE/refactor-issue.md
  .github/ISSUE_TEMPLATE/to-do-list.md
  .github/pull_request_template.md
  src/main/java/com/org/qualitycore/standardinformation/controller/StandardInformationController.java
  src/main/java/com/org/qualitycore/standardinformation/model/dto/WorkplaceDTO.java
  src/main/java/com/org/qualitycore/standardinformation/model/entity/Workplace.java
  src/main/java/com/org/qualitycore/standardinformation/model/repository/WorkplaceRepository.java
  src/main/java/com/org/qualitycore/standardinformation/model/service/StandardInformationService.java
Labels: 도와주십쇼😢

#67 📑 2025-02-19 | 백엔드 스케줄표 등록 성공
  src/main/java/com/org/qualitycore/attendance/controller/ScheduleController.java
  src/main/java/com/org/qualitycore/attendance/model/dto/AttendanceDTO.java
  src/main/java/com/org/qualitycore/attendance/model/dto/EmpScheduleCreateDTO.java
  src/main/java/com/org/qualitycore/attendance/model/entity/Attendance.java
  src/main/java/com/org/qualitycore/attendance/model/repository/ScheduleRepository.java
  src/main/java/com/org/qualitycore/attendance/model/service/ScheduleService.java
  src/main/java/com/org/qualitycore/common/Message.java
Labels: 📓문서 작업📓

#85 📑 2025-02-21 | 직원 스케줄 삭제
  src/main/java/com/org/qualitycore/attendance/controller/ScheduleController.java
  src/main/java/com/org/qualitycore/attendance/model/dto/EmpScheduleCreateDTO.java
  src/main/java/com/org/qualitycore/attendance/model/entity/Attendance.java
  src/main/java/com/org/qualitycore/attendance/model/service/ScheduleService.java
Labels: 📌일거리 등록📌

#100 📑 2025-02-21 | 작업지시서 스웨거
  src/main/java/com/org/qualitycore/work/controller/WorkController.java
  src/main/java/com/org/qualitycore/work/model/dto/WorkFindAllDTO.java
  src/main/java/com/org/qualitycore/work/model/entity/Employee.java
  src/main/java/com/org/qualitycore/work/model/entity/LineMaterial.java
  src/main/java/com/org/qualitycore/work/model/entity/PlanLine.java
  src/main/java/com/org/qualitycore/work/model/entity/PlanProduct.java
  src/main/java/com/org/qualitycore/work/model/entity/WorkOrders.java
  src/main/java/com/org/qualitycore/work/model/repository/LineMaterialRepository.java
  src/main/java/com/org/qualitycore/work/model/repository/ProcessTrackingRepository.java
  src/main/java/com/org/qualitycore/work/model/repository/WorkEmployeeRepository.java
  src/main/java/com/org/qualitycore/work/model/repository/WorkPlanLineRepository.java
  src/main/java/com/org/qualitycore/work/model/repository/WorkPlanProductRepository.java
  src/main/java/com/org/qualitycore/work/model/repository/WorkRepository.java
  src/main/java/com/org/qualitycore/work/model/service/WorkService.java
Labels: 🏗️최적화 작업🚧

#108 2025-02-21 | 작업지시서 삭제 및 API 수정
  src/main/java/com/org/qualitycore/common/Pagenation.java
  src/main/java/com/org/qualitycore/productionPlan/model/dto/PlanMstDTO.java
  src/main/java/com/org/qualitycore/productionPlan/model/service/PlanService.java
  src/main/java/com/org/qualitycore/work/controller/WorkController.java
  src/main/java/com/org/qualitycore/work/model/dto/BeerRecipesDTO.java
  src/main/java/com/org/qualitycore/work/model/dto/EmployeeDTO.java
  src/main/java/com/org/qualitycore/work/model/dto/LineMaterialDTO.java
  src/main/java/com/org/qualitycore/work/model/dto/PlanInfoDTO.java
  src/main/java/com/org/qualitycore/work/model/dto/WorkFindAllDTO.java
  src/main/java/com/org/qualitycore/work/model/entity/BeerRecipesWork.java
  src/main/java/com/org/qualitycore/work/model/entity/LineMaterial.java
  src/main/java/com/org/qualitycore/work/model/entity/MaterialWarehouseWork.java
  src/main/java/com/org/qualitycore/work/model/entity/PlanLine.java
  src/main/java/com/org/qualitycore/work/model/entity/PlanMst.java
  src/main/java/com/org/qualitycore/work/model/entity/PlanProduct.java
  src/main/java/com/org/qualitycore/work/model/entity/WorkOrders.java
  src/main/java/com/org/qualitycore/work/model/repository/WorkPlanMstRepository.java
  src/main/java/com/org/qualitycore/work/model/service/WorkService.java
Labels: 📌일거리 등록📌
